# Generated by Django 5.2.11 on 2026-02-17 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=140, unique=True)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=220)),
                ("slug", models.SlugField(blank=True, max_length=240)),
                ("author", models.CharField(blank=True, max_length=180)),
                ("description", models.TextField(blank=True)),
                (
                    "cover",
                    models.ImageField(blank=True, null=True, upload_to="covers/"),
                ),
                ("pdf", models.FileField(blank=True, null=True, upload_to="pdfs/")),
                ("audio", models.FileField(blank=True, null=True, upload_to="audio/")),
                ("is_premium", models.BooleanField(default=False)),
                ("views", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "genre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="books",
                        to="catalog.genre",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["-views"], name="catalog_boo_views_fe921e_idx"
                    ),
                    models.Index(fields=["title"], name="catalog_boo_title_3a1ffe_idx"),
                    models.Index(
                        fields=["author"], name="catalog_boo_author_66025a_idx"
                    ),
                    models.Index(
                        fields=["is_premium"], name="catalog_boo_is_prem_0448f8_idx"
                    ),
                ],
            },
        ),
    ]
